-- GENERATED by `python -m shongrokhon_ml.parity` — do not edit by hand.
-- Train/serve parity: private.risk_features must equal ml/shongrokhon_ml/features.py.
begin;
\ir _helpers.psql
select plan(13);

create temp table w (name text primary key, id uuid not null);
insert into w values ('c1', pg_temp.wallet_of(pg_temp.mk_user('8801900000001', 0, null)));
insert into w values ('c2', pg_temp.wallet_of(pg_temp.mk_user('8801900000002', 0, null)));
insert into w values ('c3', pg_temp.wallet_of(pg_temp.mk_user('8801900000003', 0, null)));
insert into w values ('p1', pg_temp.wallet_of(pg_temp.mk_user('8801900000101', 0, null)));
insert into w values ('p2', pg_temp.wallet_of(pg_temp.mk_user('8801900000102', 0, null)));
insert into w values ('p3', pg_temp.wallet_of(pg_temp.mk_user('8801900000103', 0, null)));
insert into w values ('p4', pg_temp.wallet_of(pg_temp.mk_user('8801900000104', 0, null)));
insert into w values ('p5', pg_temp.wallet_of(pg_temp.mk_user('8801900000105', 0, null)));
insert into w values ('p6', pg_temp.wallet_of(pg_temp.mk_user('8801900000106', 0, null)));
insert into w values ('mA', pg_temp.wallet_of(pg_temp.mk_merchant('8801900000201', 'PARITYA', 'Parity mA'), 'merchant'));
insert into w values ('mB', pg_temp.wallet_of(pg_temp.mk_merchant('8801900000202', 'PARITYB', 'Parity mB'), 'merchant'));
insert into w values ('mC', pg_temp.wallet_of(pg_temp.mk_merchant('8801900000203', 'PARITYC', 'Parity mC'), 'merchant'));

insert into public.transactions (type, status, payer_wallet_id, payee_wallet_id, amount, idempotency_key, created_at)
select v.type::public.txn_type, 'SUCCESS', p.id,
       coalesce(q.id, '00000000-0000-0000-0000-00000000a001'::uuid), v.amount, gen_random_uuid(), to_timestamp(v.ts)
  from (values
  ('PAYMENT', 'c1', 'mB', 815.72, 1765412022),
  ('PAYMENT', 'c1', 'mA', 716.06, 1768175175),
  ('PAYMENT', 'c1', 'mA', 326.14, 1766373256),
  ('PAYMENT', 'c1', 'mB', 796.31, 1771630210),
  ('PAYMENT', 'c1', 'mA', 753.41, 1765690936),
  ('PAYMENT', 'c1', 'mA', 733.60, 1773530507),
  ('PAYMENT', 'c1', 'mB', 328.49, 1772547123),
  ('PAYMENT', 'c1', 'mA', 308.31, 1769533042),
  ('PAYMENT', 'c1', 'mA', 444.96, 1767359772),
  ('PAYMENT', 'c1', 'mB', 493.73, 1771373927),
  ('PAYMENT', 'c1', 'mA', 896.31, 1768542829),
  ('PAYMENT', 'c1', 'mA', 729.98, 1768793783),
  ('PAYMENT', 'c1', 'mB', 890.95, 1767525629),
  ('PAYMENT', 'c1', 'mA', 256.55, 1768200372),
  ('PAYMENT', 'c1', 'mA', 582.28, 1766274446),
  ('PAYMENT', 'c1', 'mB', 116.03, 1772191768),
  ('PAYMENT', 'c1', 'mA', 502.21, 1769733285),
  ('PAYMENT', 'c1', 'mA', 462.29, 1773267722),
  ('PAYMENT', 'c1', 'mB', 595.97, 1766591025),
  ('PAYMENT', 'c1', 'mA', 501.58, 1765651671),
  ('PAYMENT', 'c1', 'mA', 282.96, 1771275427),
  ('PAYMENT', 'c1', 'mB', 89.67, 1769283014),
  ('PAYMENT', 'c1', 'mA', 647.47, 1772736256),
  ('PAYMENT', 'c1', 'mA', 244.50, 1771913645),
  ('PAYMENT', 'c1', 'mB', 83.06, 1767346765),
  ('PAYMENT', 'c1', 'mA', 760.64, 1770383206),
  ('PAYMENT', 'c1', 'mA', 299.43, 1767841724),
  ('PAYMENT', 'c1', 'mB', 801.87, 1772241456),
  ('PAYMENT', 'c1', 'mA', 774.66, 1771966955),
  ('PAYMENT', 'c1', 'mA', 604.57, 1769171407),
  ('PAYMENT', 'c1', 'mB', 155.03, 1773212133),
  ('PAYMENT', 'c1', 'mA', 523.74, 1767167099),
  ('PAYMENT', 'c1', 'mA', 794.50, 1767296559),
  ('PAYMENT', 'c1', 'mB', 376.24, 1769188848),
  ('PAYMENT', 'c1', 'mA', 128.59, 1768018353),
  ('PAYMENT', 'c1', 'mA', 397.86, 1768407690),
  ('PAYMENT', 'c1', 'mB', 203.16, 1768406433),
  ('PAYMENT', 'c1', 'mA', 749.40, 1770784966),
  ('PAYMENT', 'c1', 'mA', 882.57, 1770111376),
  ('PAYMENT', 'c1', 'mB', 563.79, 1770297585),
  ('PAYMENT', 'c1', 'mA', 650.00, 1773570600),
  ('PAYMENT', 'c1', 'mA', 700.00, 1773575700),
  ('PAYMENT', 'c1', 'mA', 999.99, 1765800000),
  ('PAYMENT', 'c1', 'mB', 120.00, 1765799999),
  ('PAYMENT', 'c1', 'mA', 400.00, 1773576000),
  ('CASHOUT', 'c1', 'SYSTEM', 1000.00, 1772712000),
  ('CASHOUT', 'c1', 'SYSTEM', 500.00, 1770897600),
  ('PAYMENT', 'c2', 'mB', 300.00, 1773144000),
  ('PAYMENT', 'c2', 'mB', 300.00, 1773144000),
  ('PAYMENT', 'c2', 'mA', 5000.00, 1770120000),
  ('PAYMENT', 'p1', 'mA', 1000.00, 1772246993),
  ('PAYMENT', 'p2', 'mA', 1000.00, 1771746310),
  ('PAYMENT', 'p2', 'mA', 2000.00, 1772228176),
  ('PAYMENT', 'p3', 'mA', 1000.00, 1771646698),
  ('PAYMENT', 'p3', 'mA', 2000.00, 1771921412),
  ('PAYMENT', 'p3', 'mA', 2500.00, 1771530415),
  ('PAYMENT', 'p4', 'mA', 1000.00, 1770682744),
  ('PAYMENT', 'p4', 'mA', 2000.00, 1773120017),
  ('PAYMENT', 'p4', 'mA', 2500.00, 1771877616),
  ('PAYMENT', 'p4', 'mA', 450.50, 1772244492),
  ('PAYMENT', 'p5', 'mA', 1000.00, 1772493422),
  ('PAYMENT', 'p5', 'mA', 2000.00, 1772851558),
  ('PAYMENT', 'p5', 'mA', 2500.00, 1773417965),
  ('PAYMENT', 'p5', 'mA', 450.50, 1772358845),
  ('PAYMENT', 'p5', 'mA', 1000.00, 1771077694),
  ('PAYMENT', 'p6', 'mA', 1000.00, 1773283566),
  ('PAYMENT', 'p6', 'mA', 2000.00, 1772347933),
  ('PAYMENT', 'p6', 'mA', 2500.00, 1770649288),
  ('PAYMENT', 'p6', 'mA', 450.50, 1770698763),
  ('PAYMENT', 'p6', 'mA', 1000.00, 1772925828),
  ('PAYMENT', 'p6', 'mA', 2000.00, 1773553044),
  ('PAYMENT', 'p1', 'mA', 3000.00, 1773057600),
  ('PAYMENT', 'p2', 'mA', 3000.00, 1773057600),
  ('CASHOUT', 'mA', 'SYSTEM', 50.00, 1756296000),
  ('CASHOUT', 'mA', 'SYSTEM', 2179.00, 1773540263),
  ('CASHOUT', 'mA', 'SYSTEM', 1251.00, 1772330570),
  ('CASHOUT', 'mA', 'SYSTEM', 2685.00, 1773343338),
  ('CASHOUT', 'mA', 'SYSTEM', 2155.00, 1772240432),
  ('CASHOUT', 'mA', 'SYSTEM', 829.00, 1771457228),
  ('CASHOUT', 'mA', 'SYSTEM', 2612.00, 1772366551),
  ('CASHOUT', 'mA', 'SYSTEM', 2850.00, 1773058200),
  ('CASHOUT', 'mA', 'SYSTEM', 700.00, 1772884800)
  ) as v (type, payer, payee, amount, ts)
  join w p on p.name = v.payer
  left join w q on q.name = v.payee;

-- Keys whose values differ by more than 1e-6 (relative), as {key: [sql, python]}.
create or replace function pg_temp.feature_diff(p_got jsonb, p_want jsonb) returns jsonb language sql as $$
  select coalesce(jsonb_object_agg(k, jsonb_build_array(p_got -> k, p_want -> k)), '{}'::jsonb)
    from (select jsonb_object_keys(p_want) as k union select jsonb_object_keys(p_got)) keys
   where p_got -> k is null or p_want -> k is null
      or abs((p_got ->> k)::float8 - (p_want ->> k)::float8) > 1e-6 * greatest(1, abs((p_want ->> k)::float8));
$$;

select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c1'), (select id from w where name = 'mA'), 500.00, to_timestamp(1773576000)), '{"amount": 500.0, "amount_to_median": 0.9195148639577759, "amount_to_merchant_median": 0.8270340903452039, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 0.0, "log_amount": 6.2166061010848646, "merchant_age_days": 91.71677083333333, "merchant_cashout_lag_min": 379.15, "merchant_cashout_ratio_7d": 0.4807461599200792, "merchant_distinct_payers_30d": 7.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.5357142857142857, "payer_cashout_count_30d": 1.0, "payer_hour_share": 0.2, "payer_median_amount_90d": 543.765, "payer_merchant_count_10m": 1.0, "payer_merchant_prior_count": 27.0, "payer_txn_count_1h": 1.0, "payer_txn_count_90d": 40.0}'::jsonb), '{}'::jsonb, 'parity q1: c1 -> mA 500.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c1'), (select id from w where name = 'mA'), 5000.00, to_timestamp(1773576000)), '{"amount": 5000.0, "amount_to_median": 9.19514863957776, "amount_to_merchant_median": 8.27034090345204, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 1.0, "log_amount": 8.517393171418904, "merchant_age_days": 91.71677083333333, "merchant_cashout_lag_min": 379.15, "merchant_cashout_ratio_7d": 0.4807461599200792, "merchant_distinct_payers_30d": 7.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.5357142857142857, "payer_cashout_count_30d": 1.0, "payer_hour_share": 0.2, "payer_median_amount_90d": 543.765, "payer_merchant_count_10m": 1.0, "payer_merchant_prior_count": 27.0, "payer_txn_count_1h": 1.0, "payer_txn_count_90d": 40.0}'::jsonb), '{}'::jsonb, 'parity q2: c1 -> mA 5000.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c1'), (select id from w where name = 'mB'), 1234.56, to_timestamp(1773579600)), '{"amount": 1234.56, "amount_to_median": 2.4066669915687897, "amount_to_merchant_median": 3.2813098022538805, "hour_cos": 0.2588190451025203, "hour_sin": -0.9659258262890684, "is_night": 0.0, "is_round_100": 0.0, "is_round_1000": 0.0, "log_amount": 7.119279587584186, "merchant_age_days": 94.53215277777778, "merchant_cashout_lag_min": 1440.0, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 2.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.0, "payer_cashout_count_30d": 1.0, "payer_hour_share": 0.15, "payer_median_amount_90d": 512.975, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 13.0, "payer_txn_count_1h": 1.0, "payer_txn_count_90d": 40.0}'::jsonb), '{}'::jsonb, 'parity q3: c1 -> mB 1234.56');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c1'), (select id from w where name = 'mC'), 300.00, to_timestamp(1773522000)), '{"amount": 300.0, "amount_to_median": 0.6024459304777396, "amount_to_merchant_median": 1.0, "hour_cos": 0.7071067811865476, "hour_sin": 0.7071067811865475, "is_night": 1.0, "is_round_100": 1.0, "is_round_1000": 0.0, "log_amount": 5.707110264748875, "merchant_age_days": 0.0, "merchant_cashout_lag_min": 1440.0, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 0.0, "merchant_new_for_payer": 1.0, "merchant_round_share_30d": 0.0, "payer_cashout_count_30d": 1.0, "payer_hour_share": 0.07894736842105263, "payer_median_amount_90d": 497.97, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 0.0, "payer_txn_count_1h": 0.0, "payer_txn_count_90d": 38.0}'::jsonb), '{}'::jsonb, 'parity q4: c1 -> mC 300.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c2'), (select id from w where name = 'mB'), 300.00, to_timestamp(1773576000)), '{"amount": 300.0, "amount_to_median": 1.0, "amount_to_merchant_median": 1.0, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 0.0, "log_amount": 5.707110264748875, "merchant_age_days": 94.49048611111111, "merchant_cashout_lag_min": 1440.0, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 2.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.0, "payer_cashout_count_30d": 0.0, "payer_hour_share": 1.0, "payer_median_amount_90d": 300.0, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 2.0, "payer_txn_count_1h": 0.0, "payer_txn_count_90d": 3.0}'::jsonb), '{}'::jsonb, 'parity q5: c2 -> mB 300.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c2'), (select id from w where name = 'mA'), 10000.00, to_timestamp(1773144060)), '{"amount": 10000.0, "amount_to_median": 33.333333333333336, "amount_to_merchant_median": 2.0, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 1.0, "log_amount": 9.210440366976517, "merchant_age_days": 86.71746527777778, "merchant_cashout_lag_min": 379.15, "merchant_cashout_ratio_7d": 0.30478721988552016, "merchant_distinct_payers_30d": 7.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.56, "payer_cashout_count_30d": 0.0, "payer_hour_share": 1.0, "payer_median_amount_90d": 300.0, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 1.0, "payer_txn_count_1h": 2.0, "payer_txn_count_90d": 3.0}'::jsonb), '{}'::jsonb, 'parity q6: c2 -> mA 10000.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c3'), (select id from w where name = 'mA'), 2000.00, to_timestamp(1773576000)), '{"amount": 2000.0, "amount_to_median": 1.0, "amount_to_merchant_median": 1.0, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 1.0, "log_amount": 7.601402334583733, "merchant_age_days": 91.71677083333333, "merchant_cashout_lag_min": 379.15, "merchant_cashout_ratio_7d": 0.4807461599200792, "merchant_distinct_payers_30d": 7.0, "merchant_new_for_payer": 1.0, "merchant_round_share_30d": 0.5357142857142857, "payer_cashout_count_30d": 0.0, "payer_hour_share": 0.0, "payer_median_amount_90d": 0.0, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 0.0, "payer_txn_count_1h": 0.0, "payer_txn_count_90d": 0.0}'::jsonb), '{}'::jsonb, 'parity q7: c3 -> mA 2000.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c3'), (select id from w where name = 'mC'), 0.01, to_timestamp(1773576000)), '{"amount": 0.01, "amount_to_median": 1.0, "amount_to_merchant_median": 1.0, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 0.0, "is_round_1000": 0.0, "log_amount": 0.009950330853168083, "merchant_age_days": 0.0, "merchant_cashout_lag_min": 1440.0, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 0.0, "merchant_new_for_payer": 1.0, "merchant_round_share_30d": 0.0, "payer_cashout_count_30d": 0.0, "payer_hour_share": 0.0, "payer_median_amount_90d": 0.0, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 0.0, "payer_txn_count_1h": 0.0, "payer_txn_count_90d": 0.0}'::jsonb), '{}'::jsonb, 'parity q8: c3 -> mC 0.01');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'p1'), (select id from w where name = 'mA'), 3000.00, to_timestamp(1773057601)), '{"amount": 3000.0, "amount_to_median": 1.5, "amount_to_merchant_median": 1.5, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 1.0, "log_amount": 8.006700845440367, "merchant_age_days": 85.71678240740741, "merchant_cashout_lag_min": 554.0333333333333, "merchant_cashout_ratio_7d": 0.06574331742658114, "merchant_distinct_payers_30d": 7.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.5416666666666666, "payer_cashout_count_30d": 0.0, "payer_hour_share": 0.5, "payer_median_amount_90d": 2000.0, "payer_merchant_count_10m": 1.0, "payer_merchant_prior_count": 2.0, "payer_txn_count_1h": 1.0, "payer_txn_count_90d": 2.0}'::jsonb), '{}'::jsonb, 'parity q9: p1 -> mA 3000.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'p6'), (select id from w where name = 'mA'), 2500.00, to_timestamp(1774180800)), '{"amount": 2500.0, "amount_to_median": 1.6666666666666667, "amount_to_merchant_median": 1.6666666666666667, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 0.0, "log_amount": 7.824445930877619, "merchant_age_days": 98.71677083333333, "merchant_cashout_lag_min": 204.26666666666668, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 7.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.5384615384615384, "payer_cashout_count_30d": 0.0, "payer_hour_share": 0.0, "payer_median_amount_90d": 1500.0, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 6.0, "payer_txn_count_1h": 0.0, "payer_txn_count_90d": 6.0}'::jsonb), '{}'::jsonb, 'parity q10: p6 -> mA 2500.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'c1'), (select id from w where name = 'mA'), 650.00, to_timestamp(1765800001)), '{"amount": 650.0, "amount_to_median": 0.8627440570207457, "amount_to_merchant_median": 0.8627440570207457, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 0.0, "is_round_1000": 0.0, "log_amount": 6.478509642208569, "merchant_age_days": 1.7167824074074074, "merchant_cashout_lag_min": 1440.0, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 1.0, "merchant_new_for_payer": 0.0, "merchant_round_share_30d": 0.0, "payer_cashout_count_30d": 0.0, "payer_hour_share": 0.4, "payer_median_amount_90d": 753.41, "payer_merchant_count_10m": 1.0, "payer_merchant_prior_count": 3.0, "payer_txn_count_1h": 2.0, "payer_txn_count_90d": 5.0}'::jsonb), '{}'::jsonb, 'parity q11: c1 -> mA 650.00');
select is(pg_temp.feature_diff(private.risk_features((select id from w where name = 'p3'), (select id from w where name = 'mB'), 100.00, to_timestamp(1777032000)), '{"amount": 100.0, "amount_to_median": 0.05, "amount_to_merchant_median": 1.0, "hour_cos": -1.8369701987210297e-16, "hour_sin": -1.0, "is_night": 0.0, "is_round_100": 1.0, "is_round_1000": 0.0, "log_amount": 4.61512051684126, "merchant_age_days": 134.49048611111112, "merchant_cashout_lag_min": 1440.0, "merchant_cashout_ratio_7d": 0.0, "merchant_distinct_payers_30d": 0.0, "merchant_new_for_payer": 1.0, "merchant_round_share_30d": 0.0, "payer_cashout_count_30d": 0.0, "payer_hour_share": 0.0, "payer_median_amount_90d": 2000.0, "payer_merchant_count_10m": 0.0, "payer_merchant_prior_count": 0.0, "payer_txn_count_1h": 0.0, "payer_txn_count_90d": 3.0}'::jsonb), '{}'::jsonb, 'parity q12: p3 -> mB 100.00');

select is((select array_agg(k order by k) from jsonb_object_keys(private.risk_features(
  (select id from w where name = 'c3'), (select id from w where name = 'mC'), 1, now())) k),
  array['amount', 'amount_to_median', 'amount_to_merchant_median', 'hour_cos', 'hour_sin', 'is_night', 'is_round_100', 'is_round_1000', 'log_amount', 'merchant_age_days', 'merchant_cashout_lag_min', 'merchant_cashout_ratio_7d', 'merchant_distinct_payers_30d', 'merchant_new_for_payer', 'merchant_round_share_30d', 'payer_cashout_count_30d', 'payer_hour_share', 'payer_median_amount_90d', 'payer_merchant_count_10m', 'payer_merchant_prior_count', 'payer_txn_count_1h', 'payer_txn_count_90d'], 'risk_features returns exactly the model feature set');

select * from finish();
rollback;
