"""Writes supabase/tests/05_feature_parity.test.sql: a pgTAP test that loads a
small event log and checks `private.risk_features` against the Python
features for the same queries. This stops training (Python) and serving (SQL)
from drifting apart.

    python -m shongrokhon_ml.parity
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pandas as pd

from . import features as F

OUT = Path(__file__).resolve().parents[2] / "supabase" / "tests" / "05_feature_parity.test.sql"
BASE = 1773576000  # 2026-03-15 12:00 UTC (18:00 Dhaka)
DAY = 86400
SYSTEM_WALLET = "00000000-0000-0000-0000-00000000a001"

CUSTOMERS = {"c1": "8801900000001", "c2": "8801900000002", "c3": "8801900000003",
             **{f"p{i}": f"88019000001{i:02d}" for i in range(1, 7)}}
MERCHANTS = {"mA": ("8801900000201", "PARITYA"), "mB": ("8801900000202", "PARITYB"), "mC": ("8801900000203", "PARITYC")}


def fixture() -> tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(7)
    ev = []

    def pay(payer, payee, amount, ts):
        ev.append(("PAYMENT", payer, payee, float(amount), int(ts)))

    def cash(wallet, amount, ts):
        ev.append(("CASHOUT", wallet, "SYSTEM", float(amount), int(ts)))

    # c1: an established customer over ~100 days, several hours, one night payment.
    for k in range(40):
        ts = BASE - int(rng.integers(1, 100 * DAY))
        pay("c1", "mA" if k % 3 else "mB", round(float(rng.uniform(80, 900)), 2), ts)
    pay("c1", "mA", 650.0, BASE - 2 * 3600 + 1800)   # 30 minutes into the last hour window
    pay("c1", "mA", 700.0, BASE - 300)               # 5 minutes ago (10-minute window)
    pay("c1", "mA", 999.99, BASE - 90 * DAY)         # exactly on the 90-day boundary: included
    pay("c1", "mB", 120.0, BASE - 90 * DAY - 1)      # 1 s outside the window: excluded
    pay("c1", "mA", 400.0, BASE)                     # at query time: excluded (strictly before)
    cash("c1", 1000.0, BASE - 10 * DAY)
    cash("c1", 500.0, BASE - 31 * DAY)
    # c2: sparse history.
    pay("c2", "mB", 300.0, BASE - 5 * DAY)
    pay("c2", "mB", 300.0, BASE - 5 * DAY)           # same timestamp twice
    pay("c2", "mA", 5000.0, BASE - 40 * DAY)
    # Other payers into mA, round and non-round amounts, two at the same instant.
    for i in range(1, 7):
        for k in range(i):
            pay(f"p{i}", "mA", [1000.0, 2000.0, 2500.0, 450.5][k % 4], BASE - int(rng.integers(1, 35 * DAY)))
    pay("p1", "mA", 3000.0, BASE - 6 * DAY)
    pay("p2", "mA", 3000.0, BASE - 6 * DAY)
    # mA cash-outs: one before any receipt (lag cap), several fast, one old.
    cash("mA", 50.0, BASE - 200 * DAY)
    for k in range(6):
        cash("mA", float(rng.integers(500, 3000)), BASE - int(rng.integers(1, 29 * DAY)))
    cash("mA", 2850.0, BASE - 6 * DAY + 600)
    cash("mA", 700.0, BASE - 8 * DAY)
    events = pd.DataFrame(ev, columns=["type", "payer", "payee", "amount", "ts"])

    q = [
        ("c1", "mA", 500.0, BASE),
        ("c1", "mA", 5000.0, BASE),
        ("c1", "mB", 1234.56, BASE + 3600),
        ("c1", "mC", 300.0, BASE - 15 * 3600),        # 03:00 Dhaka, merchant with no receipts
        ("c2", "mB", 300.0, BASE),
        ("c2", "mA", 10000.0, BASE - 5 * DAY + 60),
        ("c3", "mA", 2000.0, BASE),                    # no history at all
        ("c3", "mC", 0.01, BASE),
        ("p1", "mA", 3000.0, BASE - 6 * DAY + 1),
        ("p6", "mA", 2500.0, BASE + 7 * DAY),
        ("c1", "mA", 650.0, BASE - 90 * DAY + 1),
        ("p3", "mB", 100.0, BASE + 40 * DAY),
    ]
    queries = pd.DataFrame(q, columns=["payer", "payee", "amount", "ts"])
    return events, queries


def sql_num(x: float) -> str:
    return repr(float(x))


def render(events: pd.DataFrame, queries: pd.DataFrame) -> str:
    history = F.History(events)
    expected = F.compute(history, queries)
    lines = [
        "-- GENERATED by `python -m shongrokhon_ml.parity` — do not edit by hand.",
        "-- Train/serve parity: private.risk_features must equal ml/shongrokhon_ml/features.py.",
        "begin;",
        "\\ir _helpers.psql",
        f"select plan({len(queries) + 1});",
        "",
        "create temp table w (name text primary key, id uuid not null);",
    ]
    for name, phone in CUSTOMERS.items():
        lines.append(f"insert into w values ('{name}', pg_temp.wallet_of(pg_temp.mk_user('{phone}', 0, null)));")
    for name, (phone, mid) in MERCHANTS.items():
        lines.append(f"insert into w values ('{name}', pg_temp.wallet_of(pg_temp.mk_merchant('{phone}', '{mid}', 'Parity {name}'), 'merchant'));")
    values = ",\n  ".join(
        f"('{e.type}', '{e.payer}', '{e.payee}', {e.amount:.2f}, {int(e.ts)})" for e in events.itertuples(index=False)
    )
    lines += [
        "",
        "insert into public.transactions (type, status, payer_wallet_id, payee_wallet_id, amount, idempotency_key, created_at)",
        "select v.type::public.txn_type, 'SUCCESS', p.id,",
        f"       coalesce(q.id, '{SYSTEM_WALLET}'::uuid), v.amount, gen_random_uuid(), to_timestamp(v.ts)",
        "  from (values\n  " + values + "\n  ) as v (type, payer, payee, amount, ts)",
        "  join w p on p.name = v.payer",
        "  left join w q on q.name = v.payee;",
        "",
        "-- Keys whose values differ by more than 1e-6 (relative), as {key: [sql, python]}.",
        "create or replace function pg_temp.feature_diff(p_got jsonb, p_want jsonb) returns jsonb language sql as $$",
        "  select coalesce(jsonb_object_agg(k, jsonb_build_array(p_got -> k, p_want -> k)), '{}'::jsonb)",
        "    from (select jsonb_object_keys(p_want) as k union select jsonb_object_keys(p_got)) keys",
        "   where p_got -> k is null or p_want -> k is null",
        "      or abs((p_got ->> k)::float8 - (p_want ->> k)::float8) > 1e-6 * greatest(1, abs((p_want ->> k)::float8));",
        "$$;",
        "",
    ]
    for i, (q, (_, f)) in enumerate(zip(queries.itertuples(index=False), expected.iterrows()), start=1):
        want = json.dumps({k: float(v) for k, v in f.items()}, sort_keys=True)
        lines.append(
            "select is(pg_temp.feature_diff(private.risk_features("
            f"(select id from w where name = '{q.payer}'), (select id from w where name = '{q.payee}'), "
            f"{q.amount:.2f}, to_timestamp({int(q.ts)})), '{want}'::jsonb), '{{}}'::jsonb, "
            f"'parity q{i}: {q.payer} -> {q.payee} {q.amount:.2f}');"
        )
    feature_list = ", ".join(f"'{k}'" for k in sorted(F.FEATURES))
    lines += [
        "",
        "select is((select array_agg(k order by k) from jsonb_object_keys(private.risk_features(",
        "  (select id from w where name = 'c3'), (select id from w where name = 'mC'), 1, now())) k),",
        f"  array[{feature_list}], 'risk_features returns exactly the model feature set');",
        "",
        "select * from finish();",
        "rollback;",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    events, queries = fixture()
    OUT.write_text(render(events, queries))
    print(f"wrote {OUT} ({len(events)} events, {len(queries)} queries)")


if __name__ == "__main__":
    main()
